### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 358: ordinal not in range(128)

### ISSUE THREAD

**Issue by mikaoelitiana** [thecopy/apiary2postman#28]
I have an API blueprint doc containing french text and it causes a bug in apiary2postman convertion :  
```
Traceback (most recent call last):
  File "/usr/local/bin/apiary2postman", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/apiary2postman/apiary2postman.py", line 99, in main
    input = blueprint2json(args.blueprint_input.read())
  File "/usr/local/lib/python2.7/site-packages/apiary2postman/blueprint.py", line 15, in blueprint2json
    out, err = p.communicate(blueprint.encode('utf8'))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 358: ordinal not in range(128)
```

**Comment by yurii-github** [comment]
any hotfix on this?

**Comment by thecopy** [comment]
I think this should be fixed now in 0.5.2. Try updating

**Comment by yurii-github** [comment]
`./apiary2postman.py blueprint myapi.apib > postman.dump`

worked properly now. thanks

**Comment by thecopy** [comment]
Great!
