### ISSUE TITLE
403 Error

### ISSUE THREAD

**Issue by johnwp** [thecopy/apiary2postman#5]
Thanks for the great tool. Just wanted to pass along a 403 error I'm getting:

    $ apiary2postman api <api-key> <api-name>
    Traceback (most recent call last):
    File "/usr/local/bin/apiary2postman", line 9, in <module> load_entry_point('apiary2postman==0.4.1', 'console_scripts', 'apiary2postman')()
    File "/Library/Python/2.7/site-packages/apiary2postman/apiary2postman.py", line 87, in main blueprint = fetch_blueprint(args.name[0], apikey)
    File "/Library/Python/2.7/site-packages/apiary2postman/apiary.py", line 10, in fetch_blueprint response_body = json.loads(urlopen(request).read())
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 127, in urlopen return _opener.open(url, data, timeout)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 410, in open response = meth(req, response)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 523, in http_response 'http', request, response, code, msg, hdrs)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 448, in error return self._call_chain(*args)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 382, in _call_chain result = func(*args)
    File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 531, in http_error_default raise HTTPError(req.get_full_url(), code, msg, hdrs, fp) 
    urllib2.HTTPError: HTTP Error 403: Forbidden

**Comment by thecopy** [comment]
Fixed in 653a3c0, use pip to upgrade.
